### ISSUE TITLE
Fonts in dev container

### ISSUE THREAD

**Issue by mbastani** [Kislovskiy/ChartCraftHub#20]
Hi @Kislovskiy 

Here is the solution I found for the font issue (RobotoMono not being installed in the dev container). 

In a terminal inside the contained we need to:

1. Install the fonts
```bash
sudo wget --content-disposition -P /usr/share/fonts/truetype/robotomono https://github.com/googlefonts/RobotoMono/raw/main/fonts/ttf/RobotoMono-{Bold,BoldItalic,Italic,Light,LightItalic,Medium,MediumItalic,Regular,Thin,ThinItalic}.ttf?raw=true
  ```
3. Rebuild the Linux font cache:

  ```bash
  sudo apt-get update && \
  sudo apt install fontconfig && \
  fc-cache -fv
  ```
4. Delete the matplotlib font cache and re-import mpl to rebuilt it:
  ```bash
   rm .cache/matplotlib/ -rf
  ```

Most probably step 1 could somehow be replaced by copying the exact same font from the local repo into the dev container. Also Step 3 might not be necessary if the dev container is built with the font before being started.

**Comment by Kislovskiy** [comment]
Thanks a lot, @mbastani. Indeed, matplotlib requires the font to be present in the OS before using it. 
This means that this:
https://github.com/Kislovskiy/ChartCraftHub/blob/trunk/src/chartcrafthub/ex_1_1.py#L27C5-L27C49
It doesn't work as expected, and it's probably redundant. Thanks for finding a solution to make it work inside dev containers.

I pushed the fix here: https://github.com/Kislovskiy/ChartCraftHub/commit/841753e4ed9ed5b8fef1ff2ceb89de06f34c5fc3

I'll close this issue with this.
